// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ExamenContext))]
    [Migration("20240620091633_init11")]
    partial class init11
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationCore.Domain.Client", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ApplicationCore.Domain.Colis", b =>
                {
                    b.Property<string>("LivreurFK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientFK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateLivraison")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Clientid")
                        .HasColumnType("int");

                    b.Property<string>("LivreurCIN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Poids")
                        .HasColumnType("float");

                    b.Property<double>("Volume")
                        .HasColumnType("float");

                    b.Property<double>("montant")
                        .HasColumnType("float");

                    b.HasKey("LivreurFK", "ClientFK", "DateLivraison");

                    b.HasIndex("Clientid");

                    b.HasIndex("LivreurCIN");

                    b.ToTable("Colis");
                });

            modelBuilder.Entity("ApplicationCore.Domain.Livreur", b =>
                {
                    b.Property<string>("CIN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RaisonSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CIN");

                    b.ToTable("Livreurs");
                });

            modelBuilder.Entity("ApplicationCore.Domain.Vehicule", b =>
                {
                    b.Property<string>("Matricule")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VitesseLimite")
                        .HasColumnType("int");

                    b.HasKey("Matricule");

                    b.ToTable("Vehicules");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("LivreurVehicule", b =>
                {
                    b.Property<string>("LivreursCIN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VehiculesMatricule")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LivreursCIN", "VehiculesMatricule");

                    b.HasIndex("VehiculesMatricule");

                    b.ToTable("Conduite", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Domain.Camion", b =>
                {
                    b.HasBaseType("ApplicationCore.Domain.Vehicule");

                    b.Property<int>("NbrEssieux")
                        .HasColumnType("int");

                    b.Property<int>("capacite")
                        .HasColumnType("int");

                    b.ToTable("Camion", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Domain.Voiture", b =>
                {
                    b.HasBaseType("ApplicationCore.Domain.Vehicule");

                    b.Property<int>("NbrPlaces")
                        .HasColumnType("int");

                    b.ToTable("Voiture", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Domain.Colis", b =>
                {
                    b.HasOne("ApplicationCore.Domain.Client", null)
                        .WithMany("Coliss")
                        .HasForeignKey("Clientid");

                    b.HasOne("ApplicationCore.Domain.Livreur", null)
                        .WithMany("Coliss")
                        .HasForeignKey("LivreurCIN");
                });

            modelBuilder.Entity("LivreurVehicule", b =>
                {
                    b.HasOne("ApplicationCore.Domain.Livreur", null)
                        .WithMany()
                        .HasForeignKey("LivreursCIN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Domain.Vehicule", null)
                        .WithMany()
                        .HasForeignKey("VehiculesMatricule")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicationCore.Domain.Camion", b =>
                {
                    b.HasOne("ApplicationCore.Domain.Vehicule", null)
                        .WithOne()
                        .HasForeignKey("ApplicationCore.Domain.Camion", "Matricule")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicationCore.Domain.Voiture", b =>
                {
                    b.HasOne("ApplicationCore.Domain.Vehicule", null)
                        .WithOne()
                        .HasForeignKey("ApplicationCore.Domain.Voiture", "Matricule")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicationCore.Domain.Client", b =>
                {
                    b.Navigation("Coliss");
                });

            modelBuilder.Entity("ApplicationCore.Domain.Livreur", b =>
                {
                    b.Navigation("Coliss");
                });
#pragma warning restore 612, 618
        }
    }
}
