// <auto-generated />
using System;
using Examen.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Examen.Infrastructure.Migrations
{
    [DbContext(typeof(ExamenContext))]
    partial class ExamenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Candidature", b =>
                {
                    b.Property<int>("EnseignantFk")
                        .HasColumnType("int");

                    b.Property<int>("ConcoursFK")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDepot")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEntretien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEpreuve")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dossier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Resultat")
                        .HasColumnType("bit");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.HasKey("EnseignantFk", "ConcoursFK");

                    b.HasIndex("ConcoursFK");

                    b.ToTable("candidatures");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Concours", b =>
                {
                    b.Property<int>("promotion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("promotion"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<int>("NbrEM")
                        .HasColumnType("int");

                    b.Property<int>("NbrGC")
                        .HasColumnType("int");

                    b.Property<int>("NbrGED")
                        .HasColumnType("int");

                    b.Property<int>("NbrMath")
                        .HasColumnType("int");

                    b.Property<int>("NbrTIC")
                        .HasColumnType("int");

                    b.Property<int>("Nbrlangue")
                        .HasColumnType("int");

                    b.HasKey("promotion");

                    b.ToTable("concours");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Enseignant", b =>
                {
                    b.Property<int>("Matricule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Matricule"));

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("Specialite")
                        .HasColumnType("int");

                    b.Property<string>("UPCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UPFK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Matricule");

                    b.HasIndex("UPCode");

                    b.ToTable("Enseignants");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.UP", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("uPs");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Candidature", b =>
                {
                    b.HasOne("Examen.ApplicationCore.Domain.Concours", "Concours")
                        .WithMany("Candidatures")
                        .HasForeignKey("ConcoursFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Examen.ApplicationCore.Domain.Enseignant", "Enseignant")
                        .WithMany("Candidatures")
                        .HasForeignKey("EnseignantFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concours");

                    b.Navigation("Enseignant");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Enseignant", b =>
                {
                    b.HasOne("Examen.ApplicationCore.Domain.UP", "UP")
                        .WithMany("Enseignants")
                        .HasForeignKey("UPCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UP");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Concours", b =>
                {
                    b.Navigation("Candidatures");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Enseignant", b =>
                {
                    b.Navigation("Candidatures");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.UP", b =>
                {
                    b.Navigation("Enseignants");
                });
#pragma warning restore 612, 618
        }
    }
}
